/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AdminStudentsRouteImport } from './routes/admin-students'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerPathRouteImport } from './routes/career-path'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MentorPortalRouteImport } from './routes/mentor-portal'
import { Route as MentorSessionsRouteImport } from './routes/mentor-sessions'
import { Route as MentorStudentsRouteImport } from './routes/mentor-students'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkillLabRouteImport } from './routes/skill-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin-students',
  path: '/admin-students',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPathRoute = CareerPathRouteImport.update({
  id: '/career-path',
  path: '/career-path',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorPortalRoute = MentorPortalRouteImport.update({
  id: '/mentor-portal',
  path: '/mentor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSessionsRoute = MentorSessionsRouteImport.update({
  id: '/mentor-sessions',
  path: '/mentor-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentsRoute = MentorStudentsRouteImport.update({
  id: '/mentor-students',
  path: '/mentor-students',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillLabRoute = SkillLabRouteImport.update({
  id: '/skill-lab',
  path: '/skill-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-students': typeof AdminStudentsRoute
  '/analyzing': typeof AnalyzingRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/help': typeof HelpRoute
  '/mentor-portal': typeof MentorPortalRoute
  '/mentor-sessions': typeof MentorSessionsRoute
  '/mentor-students': typeof MentorStudentsRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-lab': typeof SkillLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-students': typeof AdminStudentsRoute
  '/analyzing': typeof AnalyzingRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/help': typeof HelpRoute
  '/mentor-portal': typeof MentorPortalRoute
  '/mentor-sessions': typeof MentorSessionsRoute
  '/mentor-students': typeof MentorStudentsRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-lab': typeof SkillLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-students': typeof AdminStudentsRoute
  '/analyzing': typeof AnalyzingRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/help': typeof HelpRoute
  '/mentor-portal': typeof MentorPortalRoute
  '/mentor-sessions': typeof MentorSessionsRoute
  '/mentor-students': typeof MentorStudentsRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-lab': typeof SkillLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/admin-reports'
    | '/admin-students'
    | '/analyzing'
    | '/assessment'
    | '/auth'
    | '/career-path'
    | '/dashboard'
    | '/guidance'
    | '/help'
    | '/mentor-portal'
    | '/mentor-sessions'
    | '/mentor-students'
    | '/mentorship'
    | '/onboarding'
    | '/results'
    | '/settings'
    | '/sitemap.xml'
    | '/skill-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/admin-reports'
    | '/admin-students'
    | '/analyzing'
    | '/assessment'
    | '/auth'
    | '/career-path'
    | '/dashboard'
    | '/guidance'
    | '/help'
    | '/mentor-portal'
    | '/mentor-sessions'
    | '/mentor-students'
    | '/mentorship'
    | '/onboarding'
    | '/results'
    | '/settings'
    | '/sitemap.xml'
    | '/skill-lab'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/admin-reports'
    | '/admin-students'
    | '/analyzing'
    | '/assessment'
    | '/auth'
    | '/career-path'
    | '/dashboard'
    | '/guidance'
    | '/help'
    | '/mentor-portal'
    | '/mentor-sessions'
    | '/mentor-students'
    | '/mentorship'
    | '/onboarding'
    | '/results'
    | '/settings'
    | '/sitemap.xml'
    | '/skill-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AnalyzingRoute: typeof AnalyzingRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  CareerPathRoute: typeof CareerPathRoute
  DashboardRoute: typeof DashboardRoute
  GuidanceRoute: typeof GuidanceRoute
  HelpRoute: typeof HelpRoute
  MentorPortalRoute: typeof MentorPortalRoute
  MentorSessionsRoute: typeof MentorSessionsRoute
  MentorStudentsRoute: typeof MentorStudentsRoute
  MentorshipRoute: typeof MentorshipRoute
  OnboardingRoute: typeof OnboardingRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillLabRoute: typeof SkillLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-students': {
      id: '/admin-students'
      path: '/admin-students'
      fullPath: '/admin-students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-path': {
      id: '/career-path'
      path: '/career-path'
      fullPath: '/career-path'
      preLoaderRoute: typeof CareerPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-portal': {
      id: '/mentor-portal'
      path: '/mentor-portal'
      fullPath: '/mentor-portal'
      preLoaderRoute: typeof MentorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-sessions': {
      id: '/mentor-sessions'
      path: '/mentor-sessions'
      fullPath: '/mentor-sessions'
      preLoaderRoute: typeof MentorSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-students': {
      id: '/mentor-students'
      path: '/mentor-students'
      fullPath: '/mentor-students'
      preLoaderRoute: typeof MentorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-lab': {
      id: '/skill-lab'
      path: '/skill-lab'
      fullPath: '/skill-lab'
      preLoaderRoute: typeof SkillLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AnalyzingRoute: AnalyzingRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  CareerPathRoute: CareerPathRoute,
  DashboardRoute: DashboardRoute,
  GuidanceRoute: GuidanceRoute,
  HelpRoute: HelpRoute,
  MentorPortalRoute: MentorPortalRoute,
  MentorSessionsRoute: MentorSessionsRoute,
  MentorStudentsRoute: MentorStudentsRoute,
  MentorshipRoute: MentorshipRoute,
  OnboardingRoute: OnboardingRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillLabRoute: SkillLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
